export function buildStructuredTextReconstructionPrompt(): string {
  return [
    "You are reconstructing editable text from a cropped image selection.",
    "Return only strict JSON with no markdown, no prose, and no code fences.",
    "",
    "Response schema (JSON Schema-style):",
    "```",
    "{",
    "  schemaVersion: \"f4.2/v2\"   (required, literal string)",
    "  blocks: [                    (required, array of Block objects)",
    "    {",
    "      id: string               (required, unique identifier e.g. \"block-1\")",
    "      text: string             (required, the reconstructed text content)",
    "      bounds: {                (required)",
    "        x: number              (required, left edge in px, relative to crop)",
    "        y: number              (required, top edge in px, relative to crop)",
    "        width: number          (required, > 0)",
    "        height: number         (required, > 0)",
    "      }",
    "      style: {",
    "        fontFamily: string     (optional, e.g. \"Arial\")",
    "        fontSize: number       (optional, in px, e.g. 24)",
    "        lineHeight: number     (optional, unitless multiplier, e.g. 1.2)",
    "        kerning: number        (optional, in px, default 0)",
    "        alignment: \"left\" | \"center\" | \"right\"  (optional, default \"left\")",
    "        bold: boolean          (optional)",
    "        italic: boolean        (optional)",
    "        underline: boolean     (optional)",
    "        strikethrough: boolean (optional)",
    "",
    "        fill: Fill             (optional, defaults to solid black)",
    "          Fill is a discriminated union on \"type\":",
    "          | { type: \"solid\", color: string }",
    "          | { type: \"linear-gradient\", angle: number, stops: GradientStop[] }",
    "              angle: degrees, 0 = left-to-right, 90 = top-to-bottom",
    "              stops: minimum 2 items",
    "          | { type: \"radial-gradient\", stops: GradientStop[], centerX?: number, centerY?: number }",
    "              centerX, centerY: 0-1 normalized, optional",
    "              stops: minimum 2 items",
    "",
    "          GradientStop: { offset: number, color: string }",
    "            offset: 0-1 normalized position along the gradient",
    "            color: CSS color string (e.g. \"#ff0000\")",
    "",
    "        stroke: { color: string, width: number } | null  (optional)",
    "",
    "        effects: Effect[]      (optional, array of Effect objects)",
    "          Effect is a discriminated union on \"type\":",
    "          | { type: \"drop-shadow\", color: string, offsetX: number, offsetY: number, blur: number, opacity: number }",
    "          | { type: \"inner-shadow\", color: string, offsetX: number, offsetY: number, blur: number, opacity: number }",
    "          | { type: \"outer-glow\", color: string, blur: number, spread: number, opacity: number }",
    "          | { type: \"outline\", color: string, width: number, opacity: number }",
    "          | { type: \"color-overlay\", color: string, opacity: number }",
    "          opacity: 0-1 for all effect types",
    "      }",
    "",
    "      transform: {             (optional)",
    "        rotationDeg: number    (optional, degrees clockwise, default 0)",
    "        scaleX: number         (optional, default 1)",
    "        scaleY: number         (optional, default 1)",
    "        skewXDeg: number       (optional, degrees, default 0)",
    "        skewYDeg: number       (optional, degrees, default 0)",
    "      }",
    "",
    "      opacity: number          (optional, 0-1, default 1)",
    "      blendMode: string        (optional, CSS blend mode, default \"normal\")",
    "      boxHeight: number | null (optional, constrained box height in px or null)",
    "      confidence: number       (optional, 0-1, how certain you are about this block)",
    "      notes: string            (optional, e.g. \"partially obscured\")",
    "    }",
    "  ]",
    "}",
    "```",
    "",
    "Rules:",
    "- Coordinates must be relative to the provided crop, not the full document.",
    "- Use one block per visually distinct editable text block. Preserve grouping; do not split nearby differently styled blocks unless they are visually separate blocks.",
    "- Use the original crop for visible text appearance and the cleaned crop for background separation.",
    "- Reconstruct only visible text. Do not describe the image.",
    "- Prefer simple, accurate structure over guessing. If a style field is unclear, omit it or use a safe default.",
    "- Preserve all punctuation exactly as it appears in the image. Do not add, remove, or change punctuation marks.",
    "- For dense layouts with multiple text lines or columns, create separate blocks for each visually distinct text group. Do not merge unrelated text areas into one block.",
    "- When text blocks are close together but have different styles (size, color, weight), always use separate blocks.",
    "- Bounds must tightly wrap each text block. Do not use the full crop dimensions as bounds for individual blocks.",
    "- If the image contains no readable text, return an empty blocks array: {\"schemaVersion\": \"f4.2/v2\", \"blocks\": []}.",
    "- Include an optional confidence (0.0 to 1.0) per block indicating how certain you are about the text recognition. Omit if unsure.",
    "- Include an optional notes field per block if there is a concern about the reconstruction quality, e.g. 'partially obscured' or 'decorative font may not match'.",
  ].join("\n");
}


